name: chopper2
description: Chopper is an http client generator using source_gen and inspired from retrofit
version: 3.0.3
homepage: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  http: ">=0.11.0 <1.0.0"
  meta: ^1.1.2
  logging: ^0.11.3

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.0.0
  build_test:
  coverage: ^0.12.2
  test_coverage: ^0.3.0
  http_parser: ^3.1.3
  pedantic: ^1.0.0
  chopper2_generator: ^3.0.3
#    path: ../chopper_generator
#  chopper2_generator:
#            path: D:\AS\ASP\Prod\OpenSource\chopper\chopper2_generator
#    git:
#      url: git://github.com/humazed/chopper.git
#      path: chopper2_generator

