name: chopper_example
description: Example of Chopper
version: 0.0.1
#homepage: https://www.example.com
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#  angular: ^6.0.1
  chopper: ^3.0.0
  json_annotation: ^3.1.0
  built_value: ^7.1.0

dev_dependencies:
  build_runner: ^1.10.3
  chopper2_generator: ^3.0.4
#  build_web_compilers: ^2.0.0
  json_serializable: ^3.5.0
  built_value_generator: ^7.1.0

dependency_overrides:
  chopper2:
    path: ../chopper2
  chopper2_generator:
    path: ../chopper2_generator
  analyzer: ^0.40.4