# Created with https://github.com/dart-lang/mono_repo
language: dart

# Custom configuration
sudo: required
addons:
  chrome: stable

install:
  - gem install coveralls-lcov

jobs:
  include:
    - stage: analyze_format_test
      name: "SDK: stable - analyze_format_test chopper"
      script: ./tool/travis.sh build dartanalyzer dartfmt test
      env: PKG="chopper"
      dart: stable
    - stage: analyze_format_test
      name: "SDK: stable - analyze_format_test chopper_generator"
      script: ./tool/travis.sh dartanalyzer dartfmt
      env: PKG="chopper_generator"
      dart: stable
    - stage: analyze_format_test
      name: "SDK: stable - analyze_format_test example"
      script: ./tool/travis.sh build dartanalyzer dartfmt
      env: PKG="example"
      dart: stable
  allow_failures:
    - stage: deploy
      name: "SDK: stable - deploy chopper"
      script: ./tool/publish.sh
      env: PKG="chopper"
      dart: stable
    - stage: deploy
      name: "SDK: stable - deploy chopper_generator"
      script: ./tool/publish.sh
      env: PKG="chopper_generator"
      dart: stable
    - stage: deploy
      name: "SDK: stable - deploy example"
      script: ./tool/publish.sh
      env: PKG="example"
      dart: stable

stages:
  - analyze_format_test
  - deploy
  if: branch = master

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master
    - develop

cache:
  directories:
    - "$HOME/.pub-cache"
    - chopper/.dart_tool
    - chopper_generator/.dart_tool
    - example/.dart_tool