name: example
description: Chopper is an http client generator using source_gen and inspired from retrofit
version: 3.0.1
homepage: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  http: ">=0.11.0 <1.0.0"
  meta: ^1.2.3
  logging: ^0.11.4
  chopper2:
    path: ../../chopper2

dev_dependencies:
  test: ^1.15.4
  build_runner: ^1.10.4
  build_test:
  http_parser: ^3.1.4
  pedantic: ^1.9.2
  chopper2_generator:
    path: ../../chopper2_generator
#  chopper2_generator:
#            path: D:\AS\ASP\Prod\OpenSource\chopper\chopper2_generator
#    git:
#      url: git://github.com/humazed/chopper.git
#      path: chopper2_generator

