# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  chopper2_generator:
    target: ":chopper2_generator"
    import: "package:chopper2_generator/chopper2_generator.dart"
    builder_factories: ["chopperGeneratorFactory"]
    build_extensions: {".dart": [".chopper2.dart"]}
    auto_apply: root_package
    build_to: source