name: chopper2_generator
description: chopper2 is an http client generator using source_gen and inspired from retrofit
version: 3.0.1
homepage: https://github.com/lejard-h/chopper2
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  meta: ^1.1.2
  analyzer: '>=0.35.0 <1.0.0'
  build: ^1.0.0
  logging: ^0.11.0
  source_gen: ^0.9.0
  code_builder: ^3.0.0
  dart_style: ^1.0.10
  built_collection: ^4.0.0
  chopper2: ^3.0.0
#    path: ../chopper
#  chopper2:
#            path: D:\AS\ASP\Prod\OpenSource\chopper2\chopper2
#    git:
#      url: git://github.com/humazed/chopper2.git
#      path: chopper2


dev_dependencies:
  test: ^1.3.0
  pedantic: ^1.0.0

dependency_overrides:
#  chopper2:
#    path: ../chopper2
#  chopper2:
#    #        path: D:\AS\ASP\Prod\OpenSource\chopper2\chopper2
#    git:
#      url: git://github.com/humazed/chopper2.git
#      path: chopper2
